# SonarQube server settings
sonar.host.url=http://localhost:9000
sonar.token=squ_d1df1f648eca3cc9b8fd2bbaf47557be478d2118

# Project identification
sonar.projectKey=econ
sonar.projectName=econ
sonar.projectVersion=1.0

# Analysis settings
sonar.sources=.

# Coverage report path
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Analysis exclusions and inclusions
sonar.inclusions=**/*.js,**/*.jsx
sonar.exclusions=\
	routes/**,\
	server.js,\
	node_modules/**,\
	coverage/**,\
	playwright-report/**,\
	e2e/**,\
	server_test/**,\
	client/src/_site/**,\
	**/*.test.js,\
	**/*.test.jsx,\
	**/__tests__/**,\
	**/tests/**,\
	client/src/index.js,\
	client/src/App.js,\
	client/src/reportWebVitals.js,\
	client/src/**/setupTests.js,\
	**/*.config.js